version: 2.1

orbs:
  windows: circleci/windows@5.0.0 

jobs:
  build:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Build with MSBuild
          command: msbuild -p:Configuration=release
      - store_artifacts:
          path: x64/Release
      - persist_to_workspace:
          root: x64/Release
          paths:
            - ./

  test:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - run:
          name: Start WPR
          command: wpr -start GeneralProfile
      - attach_workspace:
          at: ./
      - run:
          name: Run normally with 8 GiB RAM consumption
          command: |
            .\HelloVCExe.exe 8192
      - run:
          name: Run native unit tests
          command: |
            & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" .\HelloVCTest.dll /InIsolation /platform:x64
      - run:
          name: Stop WPR
          command: wpr -stop wpr.etl
          when: always
      - store_artifacts:
          path: wpr.etl

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build